### PR TITLE
feat: support external controller and its override settings

### PR DESCRIPTION
**Pull request by karin0**
This adds initial support for external controller (RESTful APIs). The inbound for external controller is started when loading a profile, and override settings for `external_controller` and `secret` are added.

The default value for `external_controller` is set to `127.0.0.1:0`, indicating disabled for now, to keep compatibile behaviors and to avoid taking settings from untrusted profiles.

Still, due to how the external controller is implemented, I haven't found a way to update the inbound when `external_controller` and `secret` are changed in the profile or settings, so a restart (force stop of the app) is required to apply the changes for now.

### CODE REVIEW

**Comment by karin0** [comment]
I have rebased the changes onto the current upstream.

**Comment by wwqgtxx** [comment]
Can you confirm that the overriding of `ExternalController` works properly?

In my actual test, no overriding occurred and the settings in the configuration file were directly loaded.

**Comment by wwqgtxx** [comment]
Actually if you keep the default value of `127.0.0.1:0` unchanged, it will not override the setting in the config file.
REF: https://stackoverflow.com/questions/69008915/how-to-serialize-kotlin-data-class-with-default-values-into-json-using-kotlinx-s

**Comment by karin0** [comment]
> Actually if you keep the default value of `127.0.0.1:0` unchanged, it will not override the setting in the config file. REF: https://stackoverflow.com/questions/69008915/how-to-serialize-kotlin-data-class-with-default-values-into-json-using-kotlinx-s

That's indeed the case. Shall I add the annotation `@EncodeDefault` to fix this?

**Comment by wwqgtxx** [comment]
> > Actually if you keep the default value of `127.0.0.1:0` unchanged, it will not override the setting in the config file. REF: https://stackoverflow.com/questions/69008915/how-to-serialize-kotlin-data-class-with-default-values-into-json-using-kotlinx-s
> 
> That's indeed the case. Shall I add the annotation `@EncodeDefault` to fix this?

This should be a solution, I just wonder if adding this annotation will have other unknown side effects.

**Comment by karin0** [comment]
> > > Actually if you keep the default value of `127.0.0.1:0` unchanged, it will not override the setting in the config file. REF: https://stackoverflow.com/questions/69008915/how-to-serialize-kotlin-data-class-with-default-values-into-json-using-kotlinx-s
> > 
> > 
> > That's indeed the case. Shall I add the annotation `@EncodeDefault` to fix this?
> 
> This should be a solution, I just wonder if adding this annotation will have other unknown side effects.

Then to avoid taking the fields like `externel-controller` from the profile, could we instead discard them entirely by setting their original values to be empty during [`UnmarshalAndPatch`](https://github.com/MetaCubeX/ClashMetaForAndroid/blob/b661d94278864c5ab981644cda4054a46ea934c6/core/src/main/golang/native/config/load.go#L33) (or related flows like [`patchOverride`](https://github.com/MetaCubeX/ClashMetaForAndroid/blob/b661d94278864c5ab981644cda4054a46ea934c6/core/src/main/golang/native/config/process.go#L32)), before the override values are applied? This way, only the explicit override values would be kept.

**Comment by wwqgtxx** [comment]
> > > > Actually if you keep the default value of `127.0.0.1:0` unchanged, it will not override the setting in the config file. REF: https://stackoverflow.com/questions/69008915/how-to-serialize-kotlin-data-class-with-default-values-into-json-using-kotlinx-s
> > > 
> > > 
> > > That's indeed the case. Shall I add the annotation `@EncodeDefault` to fix this?
> > 
> > 
> > This should be a solution, I just wonder if adding this annotation will have other unknown side effects.
> 
> Then to avoid taking the fields like `externel-controller` from the profile, could we instead discard them entirely by setting their original values to be empty during [`UnmarshalAndPatch`](https://github.com/MetaCubeX/ClashMetaForAndroid/blob/b661d94278864c5ab981644cda4054a46ea934c6/core/src/main/golang/native/config/load.go#L33) (or related flows like [`patchOverride`](https://github.com/MetaCubeX/ClashMetaForAndroid/blob/b661d94278864c5ab981644cda4054a46ea934c6/core/src/main/golang/native/config/process.go#L32)), before the override values are applied? This way, only the explicit override values would be kept, so the default override values can remain `null` with no need for `@EncodeDefault`.

I think this solution is feasible. We just need to add a function before `patchOverride` to clear the value.

**Comment by karin0** [comment]
> > > > > Actually if you keep the default value of `127.0.0.1:0` unchanged, it will not override the setting in the config file. REF: https://stackoverflow.com/questions/69008915/how-to-serialize-kotlin-data-class-with-default-values-into-json-using-kotlinx-s
> > > > 
> > > > 
> > > > That's indeed the case. Shall I add the annotation `@EncodeDefault` to fix this?
> > > 
> > > 
> > > This should be a solution, I just wonder if adding this annotation will have other unknown side effects.
> > 
> > 
> > Then to avoid taking the fields like `externel-controller` from the profile, could we instead discard them entirely by setting their original values to be empty during [`UnmarshalAndPatch`](https://github.com/MetaCubeX/ClashMetaForAndroid/blob/b661d94278864c5ab981644cda4054a46ea934c6/core/src/main/golang/native/config/load.go#L33) (or related flows like [`patchOverride`](https://github.com/MetaCubeX/ClashMetaForAndroid/blob/b661d94278864c5ab981644cda4054a46ea934c6/core/src/main/golang/native/config/process.go#L32)), before the override values are applied? This way, only the explicit override values would be kept, so the default override values can remain `null` with no need for `@EncodeDefault`.
> 
> I think this solution is feasible. We just need to add a function before `patchOverride` to clear the value.

OK, I have opened #330 and it's tested to resolve this.

**Pull request merged**
