### PR TITLE
Show All Packages

### PR DESCRIPTION
**Pull request by Tindtily**
In xiaomi 14, The Google Play Store was preinstalled, it will not list in the AppList。
image

### CODE REVIEW

**Comment by Jinzedev** [comment]
ClashMetaForAndroid导入时校验后出现 For input string"62154052.5"

**Comment by Jinzedev** [comment]
For input string "62154052.5" appears after checking on ClashMetaForAndroid import.
ClashMetaForAndroid导入时校验后出现 For input string"62154052.5"

**Comment by Tindtily** [comment]
> For input string "62154052.5" appears after checking on ClashMetaForAndroid import. ClashMetaForAndroid导入时校验后出现 For input string"62154052.5"

I have no idea with this. Cause there is no issue tab, I have to make a pull request to do so. Maybe you can solve the AppList issue without my PR

**Comment by baize0rzj2** [comment]
大佬，可以改一下包名吗，比如加一个你的后缀。这样既保证了你修改的CMFA的完整性，也可以和原作者的共存

**Comment by marcushsu** [comment]
非常需要这功能，我习惯将访问控制模式设置为「仅允许已选择的应用」，然而一些系统自带的APK都没显示，譬如Google Play商店等等，每次使用前都还得回头去切换访问控制模式。

**Comment by jamesdome** [comment]
Which [meta app installer](https://techwiti.com/meta-app-installer/) package is installed on my Android 12 OS?

**Comment by dosgo** [comment]
Is there any progress? I also need this function very much

**Comment by aviraxp** [comment]
是不是没取消勾选“过滤系统应用”

**Comment by Tindtily** [comment]
> 是不是没取消勾选“过滤系统应用”

隐藏的好深😂

**Comment by Tindtily** [comment]
设置-网络-访问控制应用包列表-右上角三个点-过滤-系统应用

**Pull request closed without merging**
